language: julia
codecov: true

os:
  - osx

addons:
  ssh_known_hosts: xgitlab.cels.anl.gov
  homebrew:
    packages:
      - git-lfs
    update: true

julia:
  - 1.4
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git lfs install
  - git clone git@xgitlab.cels.anl.gov:kimk/libDsp.git
  - export DYLD_LIBRARY_PATH=$PWD/libDsp:$DYLD_LIBRARY_PATH

before_script:
  - git clone git@github.com:kibaekkim/DSP.jl.git
  - cd DSP.jl

scipt:
  - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true);'