language: julia

os: linux
dist: bionic
addons:
  ssh_known_hosts: 
    - xgitlab.cels.anl.gov
  apt:
    packages:
      - libtbb-dev

julia:
  - 1.4
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:kimk/libDsp.git
  - cd libDsp && tar -zxvf DSP.tar.gz && cd ..
  - export LD_LIBRARY_PATH=$PWD/libDsp:$PWD/libDsp/lib:$LD_LIBRARY_PATH

before_script:
  - ls # where I am?
  - ls libDsp # what do you have?

script:
  - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true);'

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'